### ISSUE TITLE
improve explanation on generated properties

### ISSUE THREAD

**Issue by george-e-d-g-e** [olta-art/olta.js#8]
When talking about generated properties in the docs it is confusing.

Line in question:
https://github.com/olta-art/olta.js/blob/b91883ca1b0394360e92c72268730d5198d6fa2e/README.md?plain=1#L136

Is there a better place to introduce this concept? Can it be handled in a clearer manner?

The reason it is useful is for updating a document you need an  id hence introducing `_id` early on. For sorting based on user you can use the `_creator` and for order you can use `_sortkey`

Currently the hidden properties are defined [here](https://github.com/olta-art/smartweave-test/blob/cec675ab36542954e3b5efafd84abee156059b99/src/contracts/actions/project/projectState.js#L117-L131) and there is `_id`, `_sortkey` and `_creator`

**Comment by terencereilly** [comment]
Ok, thanks for explaining. Right, I see both _ID and _creator properties on the contracts :) So the _sortkey property can be used to create the timeline feature, right?

**Comment by george-e-d-g-e** [comment]
>  _sortkey property can be used to create the timeline feature, right?

currently not really. It is just a counter of number of transactions on the contract. It is more for ordering as it lacks any time related data. 

May be worth adding `_timeCreated` `_timeUpdated` but... to fully implement a timeline feature my feeling is it is best not on the smart-contract and instead use an indexing service like a subgraph on `the graph`. The reason being you get all the querying power and you don't increase the fee's paid to interact.
